import React, { useEffect, useState } from 'react';
import { ActionPlan, ActionPlanStatus, ActionPlanOriginPeriodType } from '../types';
import { firebaseService } from '../services/firebaseService';

const labels: Record<ActionPlanStatus, string> = { planned: 'Planeado', in_progress: 'En ejecución', completed: 'Completado', cancelled: 'Cancelado' };
const empty = (originYear: number, originPeriodType: ActionPlanOriginPeriodType, originPeriodIndex: number): Omit<ActionPlan, 'id' | 'createdAt' | 'updatedAt'> => ({
  indicatorId: '', dashboardId: '', clientId: '', title: '', description: '', originYear, originPeriodType, originPeriodIndex,
  status: 'planned', responsible: '', startDate: new Date().toISOString().slice(0, 10), targetDate: '', progress: 0, expectedImpact: ''
});

interface Props { indicatorId: number | string; dashboardId: number | string; clientId?: string; year: number; periodType: ActionPlanOriginPeriodType; periodIndex: number; canEdit: boolean; }

export const RelatedActionPlans: React.FC<Props> = ({ indicatorId, dashboardId, clientId, year, periodType, periodIndex, canEdit }) => {
  const [plans, setPlans] = useState<ActionPlan[]>([]);
  const [state, setState] = useState<'loading' | 'saving' | 'saved' | 'error'>('loading');
  const [draft, setDraft] = useState<ActionPlan | null>(null);
  const [editing, setEditing] = useState<string | null>(null);
  const load = async () => { setState('loading'); try { setPlans(await firebaseService.getActionPlansForIndicator(indicatorId, clientId)); setState('saved'); } catch { setState('error'); } };
  useEffect(() => { void load(); }, [indicatorId, clientId]);
  const origin = (p: ActionPlan) => p.originPeriodType === 'weekly' ? `Semana ${(p.originPeriodIndex || 0) + 1} · ${p.originYear}` : `${['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][p.originPeriodIndex || 0]} ${p.originYear}`;
  const begin = (p?: ActionPlan) => setDraft(p || { ...empty(year, periodType, periodIndex), id: '', indicatorId, dashboardId, clientId: clientId?.trim().toUpperCase() || '' } as ActionPlan);
  const save = async () => { if (!draft || !draft.title.trim()) return; setState('saving'); try { if (draft.id) await firebaseService.updateActionPlan(draft.id, draft); else await firebaseService.createActionPlan(draft); setDraft(null); setEditing(null); await load(); } catch { setState('error'); } };
  const field = (key: keyof ActionPlan, value: string | number) => setDraft(d => d ? { ...d, [key]: value } : d);
  const control = 'mt-1 w-full rounded-lg border border-slate-700 bg-slate-950/80 px-3 py-2.5 text-sm text-slate-100 outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-500/30 placeholder:text-slate-500';
  return <section className="mt-6 rounded-2xl border border-cyan-500/20 bg-slate-950/30 p-6">
    <div className="flex items-center justify-between mb-4"><div><h4 className="text-sm font-black uppercase tracking-widest text-cyan-300">Planes relacionados</h4><p className="text-xs text-slate-500 mt-1">Transversales al indicador · visibles en todos los períodos</p></div>{canEdit && <button onClick={() => begin()} className="rounded-xl bg-cyan-600 px-4 py-2 text-[10px] font-black uppercase tracking-widest text-white">+ Nuevo plan</button>}</div>
    {state === 'loading' && <p className="text-xs text-slate-500">Cargando planes…</p>}{state === 'error' && <p className="text-xs text-red-400">No se pudieron cargar o guardar los planes.</p>}
    <div className="space-y-3">{plans.map(p => <div key={p.id} className="rounded-xl border border-white/5 bg-slate-900/50 p-4"><div className="flex justify-between gap-4"><div><h5 className="font-bold text-slate-100">{p.title}</h5><p className="mt-1 text-xs text-slate-400">{labels[p.status]} · {p.progress}%{p.responsible ? ` · ${p.responsible}` : ''}{p.targetDate ? ` · Meta: ${p.targetDate}` : ''}</p><p className="mt-1 text-[10px] uppercase tracking-widest text-slate-600">Origen: {origin(p)}</p></div>{canEdit && <button onClick={() => { setEditing(p.id); begin(p); }} className="text-[10px] font-black uppercase text-cyan-400">Editar</button>}</div><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-500" style={{ width: `${Math.max(0, Math.min(100, p.progress))}%` }} /></div></div>)}</div>
    {draft && <div className="mt-4 grid gap-4 rounded-xl border border-cyan-500/20 bg-slate-900/70 p-4 md:grid-cols-2"><Field label="Nombre del plan" className="col-span-full"><input autoFocus value={draft.title} onChange={e => field('title', e.target.value)} placeholder="Ej. Recuperación Comercial" className={control} /></Field><Field label="Descripción" className="col-span-full"><textarea value={draft.description || ''} onChange={e => field('description', e.target.value)} placeholder="Describe el objetivo y las acciones principales" className={`${control} min-h-20`} /></Field><Field label="Estado"><select value={draft.status} onChange={e => field('status', e.target.value)} className={control}>{Object.entries(labels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Responsable"><input value={draft.responsible || ''} onChange={e => field('responsible', e.target.value)} placeholder="Persona responsable" className={control} /></Field><Field label="Fecha de inicio"><input type="date" value={draft.startDate || ''} onChange={e => field('startDate', e.target.value)} className={control} /></Field><Field label="Fecha objetivo"><input type="date" value={draft.targetDate || ''} onChange={e => field('targetDate', e.target.value)} className={control} /></Field><Field label="Avance (%)"><div className="relative"><input type="number" min="0" max="100" value={draft.progress} onChange={e => field('progress', Math.max(0, Math.min(100, Number(e.target.value))))} aria-label="Avance (%)" className={`${control} pr-9`} /><span className="absolute right-3 top-3 text-sm font-bold text-cyan-300">%</span></div></Field><Field label="Impacto esperado"><input value={draft.expectedImpact || ''} onChange={e => field('expectedImpact', e.target.value)} placeholder="Resultado esperado" className={control} /></Field><p className="col-span-full border-t border-white/5 pt-3 text-[10px] uppercase tracking-widest text-slate-500">Origen: {origin(draft)} <span className="normal-case tracking-normal text-slate-600">(metadata histórica · no editable)</span></p><div className="col-span-full flex justify-end gap-3"><button onClick={() => setDraft(null)} className="text-xs text-slate-400">Cancelar</button><button disabled={state === 'saving'} onClick={() => void save()} className="rounded-lg bg-cyan-600 px-5 py-2 text-xs font-bold text-white">{state === 'saving' ? 'Guardando…' : 'Guardar plan'}</button></div></div>}
  </section>;
};

const Field = ({ label, children, className = '' }: { label: string; children: React.ReactNode; className?: string }) => <label className={className}><span className="text-[10px] font-black uppercase tracking-widest text-slate-300">{label}</span>{children}</label>;
