import { formatCaptureCount, getCaptureSummaryForPeriod, makeCaptureEntry } from './smartCapture';
const m=(year:number,monthIndex:number)=>({frequency:'monthly' as const,year,monthIndex});
const item=(id:number, goal:number|null, progress:number|null, start:any, marked=true, progressMarked=marked)=>{const goals=Array(12).fill(null),values=Array(12).fill(null),goalMarks=Array(12).fill(false),progressMarks=Array(12).fill(false);goals[7]=goal;values[7]=progress;goalMarks[7]=marked;progressMarks[7]=progressMarked;return makeCaptureEntry({id,indicator:'KPI',weight:1,monthlyGoals:goals,monthlyProgress:values,monthlyGoalCaptured:goalMarks,monthlyProgressCaptured:progressMarks,unit:'u',type:'accumulative',goalType:'maximize'} as any,m(2026,7),m(2026,7),start);};
test('7 of 7 required out of 10 total is 100, never 70',()=>{const entries=[...Array.from({length:7},(_,i)=>item(i,1,0,m(2026,7))),...Array.from({length:3},(_,i)=>item(i+7,null,null,m(2026,9)))];const s=getCaptureSummaryForPeriod(entries);expect(s).toMatchObject({totalKpis:10,requiredKpis:7,capturedKpis:7,completeRequiredKpis:7,notRequiredKpis:3,capturePercent:100});});
test('monthly cross-year keeps December 2026 before January 2027',()=>{const entry=makeCaptureEntry({id:20,indicator:'KPI',weight:1,monthlyGoals:Array(12).fill(1),monthlyProgress:Array(12).fill(1),monthlyGoalCaptured:Array(12).fill(true),monthlyProgressCaptured:Array(12).fill(true),unit:'u',type:'accumulative',goalType:'maximize'} as any,m(2027,0),m(2027,0),m(2026,11));expect(getCaptureSummaryForPeriod([entry]).capturePercent).toBe(100);});
test('separates missing goal and progress and leaves zero legacy ambiguous',()=>{const s=getCaptureSummaryForPeriod([item(1,null,null,m(2026,7),false,false),item(2,1,null,m(2026,7),true,false),item(3,0,0,m(2026,7),true,true)]);expect(s).toMatchObject({requiredKpis:3,missingGoalKpis:1,missingProgressKpis:1,capturedKpis:1});});
test('no obligations returns null rather than invented 100',()=>expect(getCaptureSummaryForPeriod([item(1,null,null,m(2026,9))]).capturePercent).toBeNull());
test('5 of 7 is 71.428 and distinguishes missing meta/progress',()=>{const entries=[...Array.from({length:5},(_,i)=>item(i,1,0,m(2026,7))),item(5,null,null,m(2026,7),false,false),item(6,1,null,m(2026,7),true,false),...Array.from({length:3},(_,i)=>item(i+7,null,null,m(2026,9)))];const s=getCaptureSummaryForPeriod(entries);expect(s.capturePercent).toBeCloseTo(71.42857);expect(s).toMatchObject({requiredKpis:7,capturedKpis:5,missingGoalKpis:1,missingProgressKpis:1,notRequiredKpis:3});});
test('presentation keeps real zero and uses dash only for non-applicable counters',()=>{expect(formatCaptureCount(0,false)).toBe('0');expect(formatCaptureCount(0,true)).toBe('—');expect(formatCaptureCount(10,true)).toBe('—');});
