import React, { useEffect, useMemo, useState } from 'react';
import { ActionPlan, ActionPlanStatus, Dashboard } from '../../types';
import { firebaseService } from '../../services/firebaseService';
import { calculateActionPlanProgress } from '../../utils/actionPlanLogic';
export { calculateActionPlanProgress, deriveActionPlanStatus, getActivityTrafficLight } from '../../utils/actionPlanLogic';

const statusLabels: Record<ActionPlanStatus, string> = { planned: 'Planeado', in_progress: 'En ejecución', completed: 'Completado', cancelled: 'Cancelado' };
type Enriched = ActionPlan & { indicator: string; area: string };
interface Props { dashboards: Dashboard[]; currentDashboard: Dashboard; canEdit?: boolean; }

export type DueCategory = 'vencido' | 'próximo' | 'normal';
export const classifyDue = (plan: Pick<ActionPlan, 'targetDate' | 'status'>, now = new Date()): DueCategory => {
  if (!plan.targetDate || plan.status === 'completed' || plan.status === 'cancelled') return 'normal';
  const target = new Date(plan.targetDate); const end = new Date(now); end.setDate(end.getDate() + 7);
  return target < now ? 'vencido' : target <= end ? 'próximo' : 'normal';
};
export const dedupePlans = (items: Enriched[]) => Array.from(new Map(items.map(item => [item.id, item])).values());
export const filterPlans = (items: Enriched[], filter: string, value: string) => items.filter(p => filter === 'Todos' || value === 'Todos' || (filter === 'Área' ? p.area === value : filter === 'Responsable' ? (p.responsible || 'Sin responsable') === value : statusLabels[p.status] === value));

export const TransversalActionPlansControl: React.FC<Props> = ({ dashboards, currentDashboard, canEdit = true }) => {
  const [plans, setPlans] = useState<Enriched[]>([]); const [filter, setFilter] = useState('Todos'); const [value, setValue] = useState('Todos'); const [selected, setSelected] = useState<Enriched | null>(null); const [message, setMessage] = useState('Cargando planes…');
  const sources = useMemo(() => (dashboards.length ? dashboards : [currentDashboard]).filter(d => !d.isAggregate), [dashboards, currentDashboard]);
  const load = async () => { try { const rows = (await Promise.all(sources.flatMap(d => (d.items || []).map(async item => ({ d, item, plans: await firebaseService.getActionPlansForIndicator(item.id, d.clientId || currentDashboard.clientId) }))))).flatMap(({ d, item, plans: ps }) => ps.map(p => ({ ...p, indicator: item.indicator, area: d.area || d.group || 'General' }))); const unique = dedupePlans(rows); setPlans(unique); setMessage(unique.length ? '' : 'No hay planes registrados.'); } catch { setMessage('No se pudieron cargar los planes.'); } };
  useEffect(() => { void load(); }, [sources]);
  const due = (p: Enriched) => classifyDue(p);
  const filtered = filterPlans(plans, filter, value);
  const active = filtered.filter(p => p.status === 'planned' || p.status === 'in_progress'); const completed = filtered.filter(p => p.status === 'completed').slice(0, 8); const attention = active.filter(p => due(p) !== 'normal');
  const options = filter === 'Área' ? [...new Set(plans.map(p => p.area))] : filter === 'Responsable' ? [...new Set(plans.map(p => p.responsible || 'Sin responsable'))] : Object.values(statusLabels);
  const save = async () => { if (!selected) return; try { await firebaseService.updateActionPlan(selected.id, selected); setSelected(null); await load(); } catch { setMessage('No se pudo guardar el plan.'); } };
  const card = (p: Enriched) => { const progress = calculateActionPlanProgress(p.activities); const completed = p.activities?.filter(a => a.progress === 100).length || 0; return <button key={p.id} onClick={() => setSelected(p)} className="w-full rounded-xl border border-white/5 bg-slate-900/60 p-4 text-left hover:border-cyan-500/40"><div className="flex justify-between gap-3"><span className="font-bold text-slate-100">{p.title}</span><span className={`text-[10px] font-black uppercase ${due(p) === 'vencido' ? 'text-rose-400' : due(p) === 'próximo' ? 'text-amber-400' : 'text-cyan-400'}`}>{due(p) !== 'normal' ? due(p) : statusLabels[p.status]}</span></div><p className="mt-1 text-xs text-slate-400">{p.indicator} · {p.area}{p.responsible ? ` · ${p.responsible}` : ''}</p><p className="mt-1 text-[10px] text-slate-500">{completed} de {p.activities?.length || 0} actividades · {progress}%{p.targetDate ? ` · Meta: ${p.targetDate}` : ''} · Origen: {p.originPeriodType === 'weekly' ? `Semana ${(p.originPeriodIndex || 0) + 1}` : `${['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][p.originPeriodIndex || 0]}`} {p.originYear}</p></button>; };
  return <div className="space-y-5"><div className="flex flex-wrap items-center gap-2"><select value={filter} onChange={e => { setFilter(e.target.value); setValue('Todos'); }} className="input"><option>Todos</option><option>Área</option><option>Responsable</option><option>Estado</option></select>{filter !== 'Todos' && <select value={value} onChange={e => setValue(e.target.value)} className="input"><option>Todos</option>{options.map(o => <option key={o}>{o}</option>)}</select>}</div>{message && <p className="text-xs text-slate-500">{message}</p>}<Group title="Próximos a vencer / vencidos" items={attention} card={card} /><Group title="Planes activos" items={active.filter(p => !attention.includes(p))} card={card} /><Group title="Completados recientemente" items={completed} card={card} />{selected && <div className="rounded-xl border border-cyan-500/30 bg-slate-900 p-4"><input value={selected.title} onChange={e => setSelected({ ...selected, title: e.target.value })} className="input w-full" /><textarea value={selected.description || ''} onChange={e => setSelected({ ...selected, description: e.target.value })} className="input mt-2 w-full" placeholder="Descripción" /><div className="mt-2 flex gap-2"><input type="number" min="0" max="100" value={selected.progress} onChange={e => setSelected({ ...selected, progress: Number(e.target.value) })} className="input" /><select value={selected.status} onChange={e => setSelected({ ...selected, status: e.target.value as ActionPlanStatus })} className="input">{Object.entries(statusLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></div><p className="mt-2 text-[10px] text-slate-500">{selected.indicator} · Origen no editable</p><div className="mt-3 flex justify-end gap-3"><button onClick={() => setSelected(null)} className="text-xs text-slate-400">Cancelar</button><button onClick={() => void save()} className="rounded-lg bg-cyan-600 px-4 py-2 text-xs font-bold text-white">Guardar</button></div></div>}</div>;
};
const Group = ({ title, items, card }: { title: string; items: Enriched[]; card: (p: Enriched) => React.ReactNode }) => <section><h3 className="mb-2 text-[10px] font-black uppercase tracking-widest text-slate-400">{title} <span className="text-slate-600">({items.length})</span></h3><div className="space-y-2">{items.map(card)}</div></section>;
